# Generated by Django 5.0 on 2024-02-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_asistencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
