# Generated by Django 5.0 on 2024-01-20 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intensivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_evento', models.DateField()),
                ('primera_fecha_pago', models.DateField()),
                ('segunda_fecha_pago', models.DateField()),
                ('lugar', models.CharField(max_length=200)),
                ('precio_primera_fecha_solo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_primera_fecha_pareja', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_segunda_fecha_solo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_segunda_fecha_pareja', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_especial', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('viene_en_pareja', models.BooleanField()),
                ('nombre_pareja', models.CharField(blank=True, max_length=200)),
                ('telefono_pareja', models.CharField(blank=True, max_length=200)),
                ('email_pareja', models.EmailField(blank=True, max_length=254)),
                ('comprobante', models.ImageField(blank=True, upload_to='comprobantes/')),
                ('intensivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intensivos.intensivo')),
            ],
        ),
    ]
