# Generated by Django 5.0 on 2024-01-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intensivo',
            name='precio_promocion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='lugar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('viene_en_pareja', models.BooleanField(default=False)),
                ('nombre_pareja', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_pareja', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_pareja', models.CharField(blank=True, max_length=15, null=True)),
                ('screenshot_pago', models.ImageField(blank=True, null=True, upload_to='pagos/')),
                ('intensivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='intensivos.intensivo')),
            ],
        ),
        migrations.DeleteModel(
            name='Asistente',
        ),
    ]
