# Generated by Django 5.0 on 2024-01-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0002_intensivo_precio_promocion_alter_intensivo_lugar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intensivo',
            name='precio_especial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='precio_primera_fecha_pareja',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='precio_primera_fecha_solo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='precio_promocion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='precio_segunda_fecha_pareja',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='intensivo',
            name='precio_segunda_fecha_solo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
