# Generated by Django 5.0 on 2024-01-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0003_alter_intensivo_precio_especial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='screenshot_pago',
            field=models.ImageField(upload_to='pagos/'),
        ),
    ]
