# Generated by Django 5.0 on 2024-01-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0004_alter_participante_screenshot_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='codigo_qr',
            field=models.ImageField(blank=True, null=True, upload_to='intensivo_qrcodes/'),
        ),
        migrations.AddField(
            model_name='participante',
            name='codigo_qr_pareja',
            field=models.ImageField(blank=True, null=True, upload_to='intensivo_qrcodes/'),
        ),
    ]
