# Generated by Django 5.0 on 2024-01-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0005_participante_codigo_qr_participante_codigo_qr_pareja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usos_maximos', models.IntegerField(default=1)),
                ('usos_actuales', models.IntegerField(default=0)),
                ('fecha_expiracion', models.DateField()),
                ('descuento_pareja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intensivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_descuento', to='intensivos.intensivo')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='codigo_descuento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='intensivos.codigodescuento'),
        ),
    ]
