# Generated by Django 5.0 on 2024-01-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0006_codigodescuento_participante_codigo_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='codigo_descuento',
        ),
        migrations.DeleteModel(
            name='CodigoDescuento',
        ),
    ]
