# Generated by Django 5.0 on 2024-01-31 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0007_remove_participante_codigo_descuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('usos_maximos', models.IntegerField()),
                ('usos_actuales', models.IntegerField(default=0)),
                ('fecha_expiracion', models.DateField()),
                ('precio_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('intensivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_descuento', to='intensivos.intensivo')),
            ],
        ),
    ]
