# Generated by Django 5.0 on 2024-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intensivos', '0008_codigodescuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='intensivo',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
